name: Deploy Vue Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo `VITE_SERVER_URL=http://47.129.21.145:8000/api/v1` >> .env
          echo "VITE_CLIENT_HOST=172.31.39.242" >> .env
          echo "VITE_CLIENT_PORT=8888" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PW }}       
      - name: Build docker image
        run: docker build -t duymt3/happyboard-fe .  
      - name: Publish image to docker hub
        run: docker push duymt3/happyboard-fe:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull duymt3/happyboard-fe:latest
      - name: Delete old container
        run: docker rm -f happyboard-fe-container
      - name: Run docker container
        run: docker run -d -it -p 80:80 --rm --name happyboard-fe-container duymt3/happyboard-fe
