name: Deploy Vue Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PW }}       
      - name: Build docker image
        run: docker build -t duymt3/happyboard-fe .  
      - name: Publish image to docker hub
        run: docker push duymt3/happyboard-fe:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull duymt3/happyboard-fe:latest
      - name: Delete old container
        run: docker rm -f happyboard-fe-container
      - name: Run docker container
        run: docker run -d -p 8888:80 --name happyboard-fe-container duymt3/happyboard-fe